package corbaConversion;


/**
* corbaConversion/IConversionRemote.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Conversion.idl
* Thursday, December 7, 2023 10:51:36 PM CET
*/

public interface IConversionRemote extends IConversionRemoteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IConversionRemote
